apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: httpbin
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=httpbin'
spec:
  type: service
  lifecycle: production
  owner: user:guest
  providesApis:
    - httpbin-api
